# Site settings
title: Lauren Haldeman
header-img: img/home-bg.jpg
email: haldeman.lauren@gmail.com
copyright_name: Lauren Haldeman
description: "Official website of writer, poet, illustrator and web designer Lauren Haldeman"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: laurenhaldeman
github_username:  wlftn
facebook_username:  Swlftn
email_username:  haldeman.lauren@gmail.com


# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog-time/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
repository_url: "https://github.com/wlftn/wlftn.github.io.git"
repository: wlftn/wlftn.github.io.git
gems: [jekyll-paginate, jekyll-feed]
