# Site settings
title: Lauren Haldeman
header-img: img/home-bg.jpg
email: haldeman.lauren@gmail.com
copyright_name: Lauren Haldeman
description: "Official website of writer, poet, illustrator and web designer Lauren Haldeman"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: laurenhaldeman
github_username:  wlftn
facebook_username:  wlftn
email_username:  haldeman.lauren@gmail.com
excerpt_separator: <!--more-->

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog-time/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
repository_url: "https://github.com/wlftn/wlftn.github.io.git"
repository: wlftn/wlftn.github.io.git
gems: [jekyll-paginate, jekyll-feed]

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# image mini_magick
mini_magick:
    thumbnail:
        source: img/photos/original
        destination: img/photos/thumbnail
        resize: "100x100"
    medium:
        source: img/photos/original
        destination: img/photos/medium
        resize: "600x400"
